//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IDUSUARIO { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public string CONTRA { get; set; }
        public Nullable<int> IDGRUPO { get; set; }
        public Nullable<int> HABILITADO { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
